### ISSUE TITLE
Freezes when disassembling MKTRIL.exe?

### ISSUE THREAD

**Issue by abdulahmad** [fonic/wcdatool#13]
Piqued my interest when I saw in your readme that this could disassemble MK Trilogy for DOS in a readable format. When I try to run it on MKTRIL.EXE, it goes for about a minute or two an then gets stuck at "Generating plain disassembly for object 1...". I can see in task manager nothing is going on because the CPU usage for python goes from 30% to 0%. Is the current version of this not able to disassemble MK Trilogy? Is it something you can fix?

edit: note that I'm using the original EXE that comes on the MK Trilogy CD, not the modified community patch or gog versions.

edit2: I do see objdump.exe tasks stopping and starting. I also see Windows Defender anti virus running at 25-30% CPU. Wondering if it's completely grinding Python to a halt for some reason.

**Comment by fonic** [comment]
If you see `objdump` processes come and go, it is doing what it's supposed to.

Windows is probably not the ideal platform, total runtime for `MKTRIL.EXE` on Linux is around 2 min for me.

Either let it run until it finished or retry with Defender being temporarily disabled.

**Comment by abdulahmad** [comment]
OK it finished. Yes, it seems like it just takes longer on Windows-- maybe update the Readme to note that it will take 30 min-1 hr on Windows?

**Comment by fonic** [comment]
Windows is not recommended by the `README` anyway (WSL is), so that's fine.

By the way, I just noticed that there is an issue with splitting the disassembly into source files. To fix it, exchange these two lines (i.e. disable deduplication):
https://github.com/fonic/wcdatool/blob/0b930a059812b172814a109fe129517b2abc6415/Wcdatool/modules/main_disassembler.py#L3048-L3049
